Testing throw error

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -295,11 +295,11 @@ jobs:
 
       - name: Slack notification
         if: ${{ steps.get-broken-link-info.outputs.SLACK_COLOR }} != undefined
-        run: echo "Slack Message here"
+        run: echo Slack Message ${{ steps.get-broken-link-info.outputs.SLACK_MESSAGE }}. Outputting color for testing ${{ steps.get-broken-link-info.outputs.SLACK_COLOR }}
 
-      - name: Exit code if danger detected
-        if: ${{ steps.get-broken-link-info.outputs.SLACK_COLOR }} == danger
-        run: exit 1
+      # - name: Exit code if danger detected
+      #   if: ${{ steps.get-broken-link-info.outputs.SLACK_COLOR }} == danger
+      #   run: exit 1
 
       - name: Cancel workflow on failure
         if: ${{ failure() }}
