streamline unit tests to run only changed shared‐app/static‐pages specs and stress‐test disallowed tests

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -189,34 +189,23 @@ jobs:
         with:
           name: unit-test-allow-list
           path: .
-
-      - name: Download E2E Test Stability Allow List
-        uses: ./.github/workflows/download-artifact
-        with:
-          name: e2e-allow-list
-          path: .
-
-      - name: Set NUM_CONTAINERS, CI_NODE_INDEX, TESTS variables
-        run: node script/github-actions/select-cypress-tests.js
-        env:
-          RUN_FULL_SUITE: false
-          CHANGED_FILE_PATHS: ${{ steps.get-changed-apps.outputs.changed_files }}
-          APP_URLS: ${{ steps.get-changed-apps.outputs.urls }}
-          APP_ENTRIES: ${{ steps.get-changed-apps.outputs.entry_names }}
-          TEST_TYPE: e2e
-
       - name: Run Unit Test Selection
         run: node script/github-actions/select-unit-tests.js
         env:
           CHANGED_FILES: ${{ steps.get-changed-apps.outputs.changed_files }}
 
+      - name: Upload artifact of Unit Tests to Run
+        if: ${{ steps.unit-tests-to-stress-test.outputs.tests == 'false' }}
+        uses: ./.github/workflows/upload-artifact
+        with:
+          name: unit-tests-to-run
+          path: unit_tests_to_run.json
+
       - name: Set output of DISALLOWED_TESTS
-        if: ${{ always() }}
         id: disallowed-tests
         run: echo "tests=$DISALLOWED_TESTS" >> $GITHUB_OUTPUT
 
       - name: Set output of UNIT_TESTS_TO_STRESS_TEST
-        if: ${{ always() }}
         id: unit-tests-to-stress-test
         run: echo "tests=$UNIT_TESTS_TO_STRESS_TEST" >> $GITHUB_OUTPUT
 
@@ -228,163 +217,65 @@ jobs:
           path: unit_tests_to_stress_test.json
 
       - name: Set output of APPS_TO_STRESS_TEST
-        if: ${{ always() }}
         id: apps-to-stress-test
         run: echo "apps_to_test=$APPS_TO_STRESS_TEST" >> $GITHUB_OUTPUT
-      
-      - name: Set output of TESTS
-        id: cypress-tests
-        run: echo selected=$TESTS >> $GITHUB_OUTPUT
-
-      - name: Upload artifact of Cypress Tests to Test
-        if: ${{ steps.cypress-tests.outputs.selected == 'true' }}
-        uses: ./.github/workflows/upload-artifact
-        with:
-          name: e2e-tests-to-test
-          path: e2e_tests_to_test.json
-
-      - name: Set output of CYPRESS_TESTS_TO_STRESS_TEST
-        id: cypress-tests-to-stress-test
-        run: echo tests=$CYPRESS_TESTS_TO_STRESS_TEST >> $GITHUB_OUTPUT
-
-      - name: Upload artifact of Cypress Tests to Stress Test
-        if: ${{ steps.cypress-tests-to-stress-test.outputs.tests == 'true' }}
-        uses: ./.github/workflows/upload-artifact
-        with:
-          name: e2e-tests-to-stress-test
-          path: e2e_tests_to_stress_test.json
-
-      - name: Set output of NUM_CONTAINERS
-        id: containers
-        run: echo num=$NUM_CONTAINERS >> $GITHUB_OUTPUT
-
-      - name: Set output of CI_NODE_INDEX
-        id: matrix
-        run: echo ci_node_index=$CI_NODE_INDEX >> $GITHUB_OUTPUT
 
   unit-tests:
     name: Unit Tests
     needs: [fetch-allow-lists, tests-prep]
     timeout-minutes: 30
     runs-on: ubuntu-16-cores-22.04
-    outputs:
-      app_folders: ${{ steps.get-changed-apps.outputs.folders }}
-      changed-files: ${{ steps.get-changed-apps.outputs.changed_files }}
-
-    env:
-      DISALLOWED_TESTS: ${{ needs.tests-prep.outputs.disallowed-tests }}
-
     strategy:
       fail-fast: false
       max-parallel: 72
-      matrix:
-        ci_node_index: [0,1,2,3,4,5,6,7,8,9]
     steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
-        with:
-          fetch-depth: 0
+    - name: Checkout
+      uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
+      with:
+        fetch-depth: 0
 
-      - name: Install dependencies
-        uses: ./.github/workflows/install
-        timeout-minutes: 30
-        with:
-          key: ${{ hashFiles('yarn.lock') }}
-          yarn_cache_folder: .cache/yarn
-          path: |
-            .cache/yarn
-            node_modules
+    - name: Install dependencies
+      uses: ./.github/workflows/install
+      timeout-minutes: 30
+      with:
+        key: ${{ hashFiles('yarn.lock') }}
+        yarn_cache_folder: .cache/yarn
+        path: |
+          .cache/yarn
+          node_modules
 
-      - name: Configure AWS credentials
-        uses: ./.github/workflows/configure-aws-credentials
-        with:
-          aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-gov-west-1
+    - name: Download Unit Tests to Run
+      uses: ./.github/workflows/download-artifact
+      with:
+        name: unit-tests-to-run
+        path: .
 
-      - name: Get va-vsp-bot token
-        uses: ./.github/workflows/inject-secrets
-        with:
-          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
-          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN
-
-      - name: Init Dashboard Data Repo
-        uses: ./.github/workflows/init-data-repo
-
-      - name: Set Up BigQuery Creds
-        uses: ./.github/workflows/configure-bigquery
-
-      - name: Fetch Unit Test Stability Allow List
-        run: yarn get-allow-list
-        working-directory: qa-standards-dashboard-data
-        env:
-          TEST_TYPE: unit_test
-      
-      - name: Check for newly added disallowed tests
-        run: node script/github-actions/double-check-allow-list.js
-        env:
-          TEST_TYPE: unit_test
-          TESTS: ${{ env.DISALLOWED_TESTS }}
-          TESTS_PROPERTY: 'DISALLOWED_TESTS'
-          
-      - name: Create test results folder
-        run: mkdir -p test-results
-
-      - name: Get changed applications
-        id: get-changed-apps
-        uses: ./.github/workflows/get-changed-apps
-        with:
-          delimiter: ','
-          output-type: 'folder'
-
-      - name: Run unit tests
-        run: yarn test:unit:gha ${APP_FOLDERS:+"{script,$APP_FOLDERS}/**/*.unit.spec.js?(x)"} --coverage --log-level verbose
-        env:
-          MOCHA_FILE: test-results/unit-tests.xml
-          CHANGED_FILES: ${{ steps.get-changed-apps.outputs.changed_files }}
-          APP_FOLDERS: ${{ steps.get-changed-apps.outputs.folders }}
-          STEP: ${{ matrix.ci_node_index }}
-          IS_STRESS_TEST: false
-          NUM_CONTAINERS: 10
-      
-      - name: Archive unit test results
-        if: ${{ always() && env.NO_APPS_TO_RUN == 'false' }}
-        uses: ./.github/workflows/upload-artifact
-        with:
-          name: unit-test-report-${{ matrix.ci_node_index }}
-          path: mocha/results
-
-      - name: Rename Coverage Summary file
-        if: ${{ env.NO_APPS_TO_RUN == 'false' }}
-        run: |
-          cd coverage
-          mv coverage-summary.json coverage-summary-${{ matrix.ci_node_index }}.json
-        
-      - name: Upload Coverage Report Artifact
-        uses: ./.github/workflows/upload-artifact
-        if: ${{ always() && env.NO_APPS_TO_RUN == 'false' }}
-        with:
-          name: unit-test-coverage-${{ matrix.ci_node_index }}
-          # path: test-results/coverage_report-${{ matrix.ci_node_index }}.txt
-          path: coverage
+    - name: Run unit tests
+      run: |
+        if [ -f unit_tests_to_run.json ]; then
+          TEST_FILES=$(jq -r '.[]' unit_tests_to_run.json | paste -sd " " -)
+          if [ -n "$TEST_FILES" ]; then
+            yarn test:unit:gha $TEST_FILES --coverage --log-level verbose
+          else
+            echo "No tests to run"
+          fi
+        else
+          echo "unit_tests_to_run.json not found"
+        fi
+      env:
+        MOCHA_FILE: test-results/unit-tests.xml
 
   unit-tests-stress-test:
     name: Unit Test Stability Review
     runs-on: ubuntu-22.04
     timeout-minutes: 30
     needs: [fetch-allow-lists, tests-prep]
-    if: ${{ always() && !cancelled() && needs.tests-prep.outputs.unit-tests-to-stress-test == 'true' && github.ref != 'refs/heads/main' && needs.fetch-allow-lists.result == 'success' && needs.tests-prep.result == 'success' }}
-
-    env:
-      APPS_TO_VERIFY: ${{ needs.tests-prep.outputs.apps-to-stress-test }}
-      DISALLOWED_TESTS: '[]'
-
+    if: ${{ always() && !cancelled() && needs.tests-prep.outputs.unit-tests-to-stress-test == 'true' && github.ref != 'refs/heads/main' }}
     strategy:
       fail-fast: false
       max-parallel: 10
       matrix:
         runs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
-
     steps:
       - name: Checkout
         uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
@@ -401,8 +292,12 @@ jobs:
             .cache/yarn
             node_modules
 
-      - name: Create test results folder
-        run: mkdir -p test-results
+      - name: Fail if disallowed tests were not run through stress test
+        run: |
+          if [ ! -f unit_tests_to_stress_test.json ]; then
+          echo "Disallowed tests detected but no stress test file present."
+          exit 1
+          fi
 
       - name: Download Unit Test Stability Allow List
         uses: ./.github/workflows/download-artifact
@@ -416,95 +311,17 @@ jobs:
           name: unit-tests-to-stress-test
           path: .
 
-      - name: Run unit tests
-        run: yarn test:unit:gha ${APP_FOLDERS:+"{script,$APP_FOLDERS}/**/*.unit.spec.js?(x)"} --coverage --log-level verbose
-        env:
-          MOCHA_FILE: test-results/unit-tests.xml
-          APP_FOLDERS: ${{ steps.get-changed-apps.outputs.folders }}
-          IS_STRESS_TEST: true
-          STEP: ${{ matrix.runs }}
-    
+      - name: Run unit tests (stress)
+        run: |
+          TEST_FILES=$(jq -r '.[]' unit_tests_to_stress_test.json | paste -sd " " -)
+          yarn test:unit:gha $TEST_FILES --coverage --log-level verbose
+
       - name: Archive unit test results
         if: ${{ always() }}
         uses: ./.github/workflows/upload-artifact
         with:
           name: unit-test-stress-test-results-${{ matrix.runs }}
           path: mocha/results
-
-  update-unit-test-allow-list:
-    name: Update Unit Test Stability Allow List
-    runs-on: ubuntu-22.04
-    needs: [unit-tests-stress-test, fetch-allow-lists]
-    if: ${{ always() && (needs.unit-tests-stress-test.result == 'success' || needs.unit-tests-stress-test.result == 'failure') }}
-    continue-on-error: true
-    env:
-      APPLICATION_LIST: ${{ needs.testing-reports-prep.outputs.app_list }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
-
-      - name: Configure AWS credentials
-        uses: ./.github/workflows/configure-aws-credentials
-        with:
-          aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-gov-west-1
-          
-
-      - name: Get va-vsp-bot token
-        uses: ./.github/workflows/inject-secrets
-        with:
-          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
-          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN
-
-      - name: Init Dashboard Data Repo
-        uses: ./.github/workflows/init-data-repo
-
-      - name: Set Up BigQuery Creds
-        uses: ./.github/workflows/configure-bigquery
-      - name: Get AWS IAM role
-        uses: ./.github/workflows/inject-secrets
-        with:
-          ssm_parameter: /frontend-team/github-actions/parameters/AWS_FRONTEND_NONPROD_ROLE
-          env_variable_name: AWS_FRONTEND_NONPROD_ROLE
-
-      - name: Set UUID for Mochawesome reports
-        run: echo "UUID=$(uuidgen)" >> $GITHUB_ENV
-
-      - name: Configure AWS Credentials (2)
-        uses: ./.github/workflows/configure-aws-credentials
-        with:
-          aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-gov-west-1
-          role: ${{ env.AWS_FRONTEND_NONPROD_ROLE }}
-          role_duration: 900
-          session_name: vsp-frontendteam-githubaction
-          
-
-      - name: Download Unit Test results
-        uses: ./.github/workflows/download-artifact
-        with:
-          pattern: unit-test-stress-test-results-*
-          path: qa-standards-dashboard-data/src/allow-list/data
-          merge-multiple: true
-
-      - name: Download Unit Test Stability Allow List
-        uses: ./.github/workflows/download-artifact
-        with:
-          name: unit-test-allow-list
-          path: qa-standards-dashboard-data
-
-      - name: Copy test results to mochawesome directory
-        run: cp -R qa-standards-dashboard-data/src/allow-list/data qa-standards-dashboard-data/src/testing-reports/data
-
-      - name: Update Unit Test Stability Allow List
-        run: yarn update-allow-list
-        working-directory: qa-standards-dashboard-data
-        env:
-          TEST_TYPE: unit_test
-          IS_CI: true
-          GITHUB_WORKFLOW_URL: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
   security-audit:
     name: Security Audit
