test new method of fetching sha by tag

diff --git a/.github/workflows/daily-deploy-production.yml b/.github/workflows/daily-deploy-production.yml
--- a/.github/workflows/daily-deploy-production.yml
+++ b/.github/workflows/daily-deploy-production.yml
@@ -1,17 +1,18 @@
 name: Daily Production Deploy
 
 on:
-  workflow_dispatch:
-    inputs:
-      release_wait:
-        description: Minutes to wait before creating release
-        required: false
-        default: '5'
-      commit_sha:
-        description: Deploy specific commit
-        required: false
-  schedule:
-    - cron: 0 19 * * 1-5
+  # workflow_dispatch:
+  #   inputs:
+  #     release_wait:
+  #       description: Minutes to wait before creating release
+  #       required: false
+  #       default: '5'
+  #     commit_sha:
+  #       description: Deploy specific commit
+  #       required: false
+  # schedule:
+  #   - cron: 0 19 * * 1-5
+  push
 
 env:
   CHANNEL_ID: C0MQ281DJ # vfs-platform-builds
@@ -67,295 +68,183 @@ jobs:
         run: echo 'RELEASE_WAIT=${{ github.event.inputs.release_wait }}' >> $GITHUB_ENV
 
       - name: Get commit sha (latest commit)
-        if: ${{ github.event.schedule != '' || (github.event_name == 'workflow_dispatch' && github.event.inputs.commit_sha == '') }}
-        run: echo 'COMMIT_SHA=${{ github.sha }}' >> $GITHUB_ENV
+        # if: ${{ github.event.schedule != '' || (github.event_name == 'workflow_dispatch' && github.event.inputs.commit_sha == '') }}
+        if: ${{ github.event_name == 'push' }}
+        run: echo 'COMMIT_SHA=$(git rev-list -n 1 ${{ github.event.inputs.tag_name }})' >> $GITHUB_ENV
 
       - name: Get commit sha (workflow_dispatch)
         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_sha != '' }}
         run: echo 'COMMIT_SHA=${{ github.event.inputs.commit_sha }}' >> $GITHUB_ENV
 
-  validate-build-status:
-    name: Validate Build Status
-    runs-on: ubuntu-latest
-    needs: set-env
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
+  # notify-start:
+  #   name: Notify Start
+  #   runs-on: ubuntu-latest
+  #   needs: set-env
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
 
-      - name: Install dependencies
-        uses: ./.github/workflows/install
-        timeout-minutes: 30
-        with:
-          key: ${{ hashFiles('yarn.lock') }}
-          yarn_cache_folder: ~/.cache/yarn
-          path: |
-            ~/.cache/yarn
-            node_modules
+  #     - name: Notify Slack
+  #       uses: ./.github/workflows/slack-notify
+  #       continue-on-error: true
+  #       env:
+  #         RELEASE_WAIT_MINUTES: ${{ needs.set-env.outputs.RELEASE_WAIT < 5 && 'a few' || needs.set-env.outputs.RELEASE_WAIT }}
+  #       with:
+  #         channel_id: ${{ env.VETS_WEBSITE_CHANNEL_ID }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         payload: | 
+  #           {
+  #             "attachments": [
+  #               {
+  #                 "color": "#07711E",
+  #                 "blocks": [
+  #                   {
+  #                     "type": "section",
+  #                     "text": {
+  #                       "type": "mrkdwn",
+  #                       "text": "Stand by, production deploy for vets-website coming up in ${{ env.RELEASE_WAIT_MINUTES }} minutes. View what's coming here: <https://github.com/${{ github.repository }}/compare/${{ needs.set-env.outputs.LATEST_TAG_VERSION }}...${{ needs.set-env.outputs.COMMIT_SHA }}>"
+  #                     }
+  #                   }
+  #                 ]
+  #               }
+  #             ]
+  #           }
 
-      - name: Validate build status
-        run: node ./script/github-actions/validate-build-status.js ${{ needs.set-env.outputs.COMMIT_SHA }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # create-release:
+  #   name: Create Release
+  #   runs-on: ubuntu-latest
+  #   needs: [set-env, notify-start]
+  #   steps:
 
-  notify-start:
-    name: Notify Start
-    runs-on: ubuntu-latest
-    needs: set-env
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
+  #     - name: Checkout
+  #       uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Notify Slack
-        uses: ./.github/workflows/slack-notify
-        continue-on-error: true
-        env:
-          RELEASE_WAIT_MINUTES: ${{ needs.set-env.outputs.RELEASE_WAIT < 5 && 'a few' || needs.set-env.outputs.RELEASE_WAIT }}
-        with:
-          channel_id: ${{ env.VETS_WEBSITE_CHANNEL_ID }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          payload: | 
-            {
-              "attachments": [
-                {
-                  "color": "#07711E",
-                  "blocks": [
-                    {
-                      "type": "section",
-                      "text": {
-                        "type": "mrkdwn",
-                        "text": "Stand by, production deploy for vets-website coming up in ${{ env.RELEASE_WAIT_MINUTES }} minutes. View what's coming here: <https://github.com/${{ github.repository }}/compare/${{ needs.set-env.outputs.LATEST_TAG_VERSION }}...${{ needs.set-env.outputs.COMMIT_SHA }}>"
-                      }
-                    }
-                  ]
-                }
-              ]
-            }
+  #     - name: Configure AWS Credentials
+  #       uses: ./.github/workflows/configure-aws-credentials
+  #       with:
+  #         aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws_region: us-gov-west-1
 
-  build:
-    name: Build
-    runs-on: self-hosted
-    needs: [set-env, notify-start, validate-build-status]
-    
-    env:
-      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem
-    
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
-        with:
-          ref: ${{ needs.set-env.outputs.COMMIT_SHA }}
+  #     - name: Get bot token from Parameter Store
+  #       uses: department-of-veterans-affairs/action-inject-ssm-secrets@latest
+  #       with:
+  #         ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
+  #         env_variable_name: VA_VSP_BOT_GITHUB_TOKEN
 
-      - name: Install dependencies
-        uses: ./.github/workflows/install
-        with:
-          key: ${{ hashFiles('yarn.lock') }}
-          yarn_cache_folder: .cache/yarn
-          path: |
-            .cache/yarn
-            node_modules
+  #     - name: Waiting to release
+  #       run: |
+  #         echo 'Waiting to release: https://github.com/${{ github.repository }}/compare/${{ needs.set-env.outputs.LATEST_TAG_VERSION }}...${{ needs.set-env.outputs.COMMIT_SHA }}'
 
-      - name: Build
-        run: yarn build --verbose --buildtype=${{ env.BUILD_ENV }}
-        timeout-minutes: 30
-
-      - name: Generate build details
-        run: |
-          cat > build/${{ env.BUILD_ENV }}/BUILD.txt << EOF
-          BUILDTYPE=${{ env.BUILD_ENV }}
-          NODE_ENV=production
-          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
-          CHANGE_TARGET=null
-          RUN_ID=${{ github.run_id }}
-          RUN_NUMBER=${{ github.run_number }}
-          REF=${{ needs.set-env.outputs.COMMIT_SHA }}
-          BUILDTIME=$(date +%s)
-          EOF
-
-      - name: Compress and archive build
-        run: tar -C build/${{ env.BUILD_ENV }} -cjf ${{ env.BUILD_ENV }}.tar.bz2 .
-
-      - name: Upload build artifact
-        uses: ./.github/workflows/upload-artifact
-        with:
-          name: ${{ env.BUILD_ENV }}.tar.bz2
-          path: ${{ env.BUILD_ENV }}.tar.bz2
-          retention-days: 1
-
-  archive:
-    name: Archive
-    runs-on: ubuntu-latest
-    needs: [set-env, build]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
-
-      - name: Download build artifact
-        uses: ./.github/workflows/download-artifact
-        with:
-          name: ${{ env.BUILD_ENV }}.tar.bz2
-
-      - name: Configure AWS credentials (1)
-        uses: ./.github/workflows/configure-aws-credentials
-        with:
-          aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-gov-west-1
-
-      - name: Get AWS IAM role
-        uses: department-of-veterans-affairs/action-inject-ssm-secrets@latest
-        with:
-          ssm_parameter: /frontend-team/github-actions/parameters/AWS_FRONTEND_NONPROD_ROLE
-          env_variable_name: AWS_FRONTEND_NONPROD_ROLE
-
-      - name: Configure AWS Credentials (2)
-        uses: ./.github/workflows/configure-aws-credentials
-        with:
-          aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-gov-west-1
-          role: ${{ env.AWS_FRONTEND_NONPROD_ROLE }}
-          role_duration: 900
-          session_name: vsp-frontendteam-githubaction
-
-      - name: Upload build
-        run: aws s3 cp ${{ env.BUILD_ENV }}.tar.bz2 s3://vetsgov-website-builds-s3-upload/${{ needs.set-env.outputs.COMMIT_SHA }}/${{ env.BUILD_ENV }}.tar.bz2 --acl public-read --region us-gov-west-1
-  
-  create-release:
-    name: Create Release
-    runs-on: ubuntu-latest
-    needs: [set-env, notify-start, validate-build-status, archive]
-    steps:
-
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
-        with:
-          fetch-depth: 0
-
-      - name: Configure AWS Credentials
-        uses: ./.github/workflows/configure-aws-credentials
-        with:
-          aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: us-gov-west-1
-
-      - name: Get bot token from Parameter Store
-        uses: department-of-veterans-affairs/action-inject-ssm-secrets@latest
-        with:
-          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
-          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN
-
-      - name: Waiting to release
-        run: |
-          echo 'Waiting to release: https://github.com/${{ github.repository }}/compare/${{ needs.set-env.outputs.LATEST_TAG_VERSION }}...${{ needs.set-env.outputs.COMMIT_SHA }}'
-
-      - name: Sleep for ${{ needs.set-env.outputs.RELEASE_WAIT }} minutes
-        uses: whatnick/wait-action@master
-        with:
-          time: ${{ needs.set-env.outputs.RELEASE_WAIT }}m
+  #     - name: Sleep for ${{ needs.set-env.outputs.RELEASE_WAIT }} minutes
+  #       uses: whatnick/wait-action@master
+  #       with:
+  #         time: ${{ needs.set-env.outputs.RELEASE_WAIT }}m
           
-      - name: Echo latest tag
-        run: echo ${{ needs.set-env.outputs.LATEST_TAG_VERSION }}
+  #     - name: Echo latest tag
+  #       run: echo ${{ needs.set-env.outputs.LATEST_TAG_VERSION }}
 
-      - name: Get next tag version
-        id: bump-tag-version
-        uses: WyriHaximus/github-action-next-semvers@v1
-        with:
-          version: ${{ needs.set-env.outputs.LATEST_TAG_VERSION }}
+  #     - name: Get next tag version
+  #       id: bump-tag-version
+  #       uses: WyriHaximus/github-action-next-semvers@v1
+  #       with:
+  #         version: ${{ needs.set-env.outputs.LATEST_TAG_VERSION }}
       
-      - name: Echo new tag version
-        run: echo ${{ steps.bump-tag-version.outputs.v_patch }}
+  #     - name: Echo new tag version
+  #       run: echo ${{ steps.bump-tag-version.outputs.v_patch }}
 
-      - name: Create tag
-        run: git tag ${{ steps.bump-tag-version.outputs.v_patch }} ${{ needs.set-env.outputs.COMMIT_SHA }} && git push origin ${{ steps.bump-tag-version.outputs.v_patch }}
+  #     - name: Create tag
+  #       run: git tag ${{ steps.bump-tag-version.outputs.v_patch }} ${{ needs.set-env.outputs.COMMIT_SHA }} && git push origin ${{ steps.bump-tag-version.outputs.v_patch }}
 
-      - name: Create release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ steps.bump-tag-version.outputs.v_patch }}
-          release_name: vets-website/${{ steps.bump-tag-version.outputs.v_patch }}
+  #     - name: Create release
+  #       uses: actions/create-release@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       with:
+  #         tag_name: ${{ steps.bump-tag-version.outputs.v_patch }}
+  #         release_name: vets-website/${{ steps.bump-tag-version.outputs.v_patch }}
 
-  deploy:
-    name: Deploy
-    runs-on: ubuntu-latest
-    needs: [set-env, create-release, get-workflow-environment]
-    environment: ${{ needs.get-workflow-environment.outputs.environment_name }}
+  # deploy:
+  #   name: Deploy
+  #   runs-on: ubuntu-latest
+  #   needs: [set-env, create-release, get-workflow-environment]
+  #   environment: ${{ needs.get-workflow-environment.outputs.environment_name }}
 
-    env:
-      DEPLOY_BUCKET: www.va.gov
-      ASSET_BUCKET: prod-va-gov-assets
+  #   env:
+  #     DEPLOY_BUCKET: www.va.gov
+  #     ASSET_BUCKET: prod-va-gov-assets
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Configure AWS credentials (1)
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-gov-west-1
+  #     - name: Configure AWS credentials (1)
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-gov-west-1
 
-      - name: Get AWS IAM role
-        uses: marvinpinto/action-inject-ssm-secrets@v1.2.1
-        with:
-          ssm_parameter: /frontend-team/github-actions/parameters/AWS_FRONTEND_PROD_ROLE
-          env_variable_name: AWS_FRONTEND_PROD_ROLE
+  #     - name: Get AWS IAM role
+  #       uses: marvinpinto/action-inject-ssm-secrets@v1.2.1
+  #       with:
+  #         ssm_parameter: /frontend-team/github-actions/parameters/AWS_FRONTEND_PROD_ROLE
+  #         env_variable_name: AWS_FRONTEND_PROD_ROLE
 
-      - name: Configure AWS Credentials (2)
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-gov-west-1
-          role-to-assume: ${{ env.AWS_FRONTEND_PROD_ROLE }}
-          role-duration-seconds: 900
-          role-session-name: vsp-frontendteam-githubaction
+  #     - name: Configure AWS Credentials (2)
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-gov-west-1
+  #         role-to-assume: ${{ env.AWS_FRONTEND_PROD_ROLE }}
+  #         role-duration-seconds: 900
+  #         role-session-name: vsp-frontendteam-githubaction
 
-      - name: Deploy
-        run: ./script/github-actions/deploy.sh -s $SRC -d $DEST -a $ASSET_DEST -v
-        env:
-          SRC: s3://vetsgov-website-builds-s3-upload/${{ needs.set-env.outputs.COMMIT_SHA }}/${{ env.BUILD_ENV }}.tar.bz2
-          DEST: s3://${{ env.DEPLOY_BUCKET }}
-          ASSET_DEST: s3://${{ env.ASSET_BUCKET }}
+  #     - name: Deploy
+  #       run: ./script/github-actions/deploy.sh -s $SRC -d $DEST -a $ASSET_DEST -v
+  #       env:
+  #         SRC: s3://vetsgov-website-builds-s3-upload/${{ needs.set-env.outputs.COMMIT_SHA }}/${{ env.BUILD_ENV }}.tar.bz2
+  #         DEST: s3://${{ env.DEPLOY_BUCKET }}
+  #         ASSET_DEST: s3://${{ env.ASSET_BUCKET }}
 
-  notify-success:
-    name: Notify Success
-    runs-on: ubuntu-latest
-    needs: deploy
+  # notify-success:
+  #   name: Notify Success
+  #   runs-on: ubuntu-latest
+  #   needs: deploy
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
 
-      - name: Notify Slack
-        uses: ./.github/workflows/slack-notify
-        continue-on-error: true
-        with:
-          payload: '{"attachments": [{"color": "#07711E","blocks": [{"type": "section","text": {"type": "mrkdwn","text": "Successfully deployed vets-website to production"}}]}]}'
-          channel_id: ${{ env.VETS_WEBSITE_CHANNEL_ID }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #     - name: Notify Slack
+  #       uses: ./.github/workflows/slack-notify
+  #       continue-on-error: true
+  #       with:
+  #         payload: '{"attachments": [{"color": "#07711E","blocks": [{"type": "section","text": {"type": "mrkdwn","text": "Successfully deployed vets-website to production"}}]}]}'
+  #         channel_id: ${{ env.VETS_WEBSITE_CHANNEL_ID }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-  notify-failure:
-    name: Notify Failure
-    runs-on: ubuntu-latest
-    if: ${{ failure() || cancelled() }}
-    needs: deploy
+  # notify-failure:
+  #   name: Notify Failure
+  #   runs-on: ubuntu-latest
+  #   if: ${{ failure() || cancelled() }}
+  #   needs: deploy
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
 
-      - name: Notify Slack
-        if: ${{ env.DSVA_SCHEDULE_ENABLED == 'true' }}
-        uses: ./.github/workflows/slack-notify
-        continue-on-error: true
-        with:
-          payload: '{"attachments": [{"color": "#FF0800","blocks": [{"type": "section","text": {"type": "mrkdwn","text": "<!here> Production deploy for vets-website has failed!: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"}}]}]}'
-          channel_id: ${{ env.VETS_WEBSITE_CHANNEL_ID }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #     - name: Notify Slack
+  #       if: ${{ env.DSVA_SCHEDULE_ENABLED == 'true' }}
+  #       uses: ./.github/workflows/slack-notify
+  #       continue-on-error: true
+  #       with:
+  #         payload: '{"attachments": [{"color": "#FF0800","blocks": [{"type": "section","text": {"type": "mrkdwn","text": "<!here> Production deploy for vets-website has failed!: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"}}]}]}'
+  #         channel_id: ${{ env.VETS_WEBSITE_CHANNEL_ID }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
